enable-magisk-update = true

# ReVanced Extended
[YouTube-Extended]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.uptodown.com/android"
version = "latest"
patches-source = "inotia00/revanced-patches"
patches-version = "v4.13.1"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
included-patches = "'Visual preferences icons'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube'"

[YT-Music-Extended]
app-name = "YT-Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.uptodown.com/android"
version = "latest"
patches-source = "inotia00/revanced-patches"
patches-version = "dev"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

# ReVanced anddea
[YouTube-anddea]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.uptodown.com/android"
version = "latest"
patches-source = "anddea/revanced-patches"
patches-version = "v2.228.0"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
build-mode = "both"

[YT-Music-anddea]
app-name = "YT-Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.uptodown.com/android"
version = "latest"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide player overlay filter'"